### ISSUE TITLE
How do I display this through notify.nvim?

### ISSUE THREAD

**Issue by TeaSpillStudios** [stsewd/spotify.nvim#12]

**Comment by stsewd** [comment]
Hi, this is already possible, you just need to install notify.nvim and the status should be displayed as a notification.

**Comment by TeaSpillStudios** [comment]
I have it installed and I can manually send notifications with lua but when pausing music for example, it does not display in the notifications, instead it displays as the following:
![image](https://user-images.githubusercontent.com/57747851/206933195-6dd5d1dc-5a95-4f75-8090-f9d979becd25.png)

**Comment by stsewd** [comment]
@TeaSpillStudios this plugin just calls to the notify api. Does any of these work for you?

`:lua vim.notify("foo")`
`:call nvim_notify("foo", 2, {})`

If they don't, you are probably missing overriding the default notify api.

**Comment by TeaSpillStudios** [comment]
The first one just returns `foo` at the bottom of my screen and the second one seems to do nothing. Sorry as this doesn't seem to be an issue with your plugin. I'll close this, thanks so much for your patience and help!
